import { Movie } from '../../../libs/omdb/src/omdb.interface';

export const moviesCollection: Movie[] = [
	{
		Title: 'Sky',
		Year: '2015',
		Rated: 'Not Rated',
		Released: '15 Apr 2016',
		Runtime: '100 min',
		Genre: 'Drama, Romance',
		Director: 'Fabienne Berthaud',
		Writer: 'Fabienne Berthaud, Pascal Arnold',
		Actors: 'Diane Kruger, Norman Reedus, Gilles Lellouche',
		Plot: 'Romy (Diane Kruger) is on holiday in the USA with her French husband, Richard (Gilles Lellouche). But the journey quickly turns into a settling of old scores for this worn out couple. After an ultimate fight, Romy decides to break fr',
		Language: 'English, French',
		Country: 'France, Germany',
		Awards: '1 nomination',
		Poster: 'https://m.media-amazon.com/images/M/MV5BMTkyNTMzMDc3MV5BMl5BanBnXkFtZTgwMzA2MTQ3ODE@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '5.9/10' },
			{ Source: 'Rotten Tomatoes', Value: '50%' },
			{ Source: 'Metacritic', Value: '55/100' },
		],
		Metascore: '55',
		imdbRating: '5.9',
		imdbVotes: '2,216',
		imdbID: 'tt4106306',
		Type: 'movie',
		DVD: '16 Aug 2016',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Skyfall',
		Year: '2012',
		Rated: 'PG-13',
		Released: '09 Nov 2012',
		Runtime: '143 min',
		Genre: 'Action, Adventure, Thriller',
		Director: 'Sam Mendes',
		Writer: 'Neal Purvis, Robert Wade, John Logan',
		Actors: 'Daniel Craig, Javier Bardem, Naomie Harris',
		Plot: "James Bond's loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.",
		Language: 'English, Turkish, Shanghainese, Portuguese, Japanese',
		Country: 'United Kingdom, United States, Turkey',
		Awards: 'Won 2 Oscars. 67 wins & 123 nominations total',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BMWZiNjE2OWItMTkwNy00ZWQzLWI0NTgtMWE0NjNiYTljN2Q1XkEyXkFqcGdeQXVyNzAwMjYxMzA@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.8/10' },
			{ Source: 'Rotten Tomatoes', Value: '92%' },
			{ Source: 'Metacritic', Value: '81/100' },
		],
		Metascore: '81',
		imdbRating: '7.8',
		imdbVotes: '677,697',
		imdbID: 'tt1074638',
		Type: 'movie',
		DVD: '12 Feb 2013',
		BoxOffice: '$304,360,277',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Man of Steel',
		Year: '2013',
		Rated: 'PG-13',
		Released: '14 Jun 2013',
		Runtime: '143 min',
		Genre: 'Action, Adventure, Sci-Fi',
		Director: 'Zack Snyder',
		Writer: 'David S. Goyer, Christopher Nolan, Jerry Siegel',
		Actors: 'Henry Cavill, Amy Adams, Michael Shannon',
		Plot: 'An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened when other survivors of his home planet invade Earth.',
		Language: 'English',
		Country: 'United States, United Kingdom',
		Awards: 'Nominated for 1 BAFTA Film Award7 wins & 46 nominations total',
		Poster: 'https://m.media-amazon.com/images/M/MV5BMTk5ODk1NDkxMF5BMl5BanBnXkFtZTcwNTA5OTY0OQ@@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.0/10' },
			{ Source: 'Rotten Tomatoes', Value: '56%' },
			{ Source: 'Metacritic', Value: '55/100' },
		],
		Metascore: '55',
		imdbRating: '7.0',
		imdbVotes: '744,495',
		imdbID: 'tt0770828',
		Type: 'movie',
		DVD: '12 Nov 2013',
		BoxOffice: '$291,045,518',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Superman',
		Year: '1978',
		Rated: 'PG',
		Released: '15 Dec 1978',
		Runtime: '143 min',
		Genre: 'Action, Adventure, Sci-Fi',
		Director: 'Richard Donner',
		Writer: 'Jerry Siegel, Joe Shuster, Mario Puzo',
		Actors: 'Christopher Reeve, Margot Kidder, Gene Hackman',
		Plot: "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.",
		Language: 'English',
		Country: 'United States, United Kingdom, Canada',
		Awards: 'Won 1 Oscar. 17 wins & 23 nominations total',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BMzA0YWMwMTUtMTVhNC00NjRkLWE2ZTgtOWEzNjJhYzNiMTlkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.3/10' },
			{ Source: 'Rotten Tomatoes', Value: '94%' },
			{ Source: 'Metacritic', Value: '81/100' },
		],
		Metascore: '81',
		imdbRating: '7.3',
		imdbVotes: '170,108',
		imdbID: 'tt0078346',
		Type: 'movie',
		DVD: '01 May 2001',
		BoxOffice: '$134,451,603',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Iron Man',
		Year: '2008',
		Rated: 'PG-13',
		Released: '02 May 2008',
		Runtime: '126 min',
		Genre: 'Action, Adventure, Sci-Fi',
		Director: 'Jon Favreau',
		Writer: 'Mark Fergus, Hawk Ostby, Art Marcum',
		Actors: 'Robert Downey Jr., Gwyneth Paltrow, Terrence Howard',
		Plot: 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
		Language: 'English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian',
		Country: 'United States, Canada',
		Awards: 'Nominated for 2 Oscars. 21 wins & 73 nominations total',
		Poster: 'https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.9/10' },
			{ Source: 'Rotten Tomatoes', Value: '94%' },
			{ Source: 'Metacritic', Value: '79/100' },
		],
		Metascore: '79',
		imdbRating: '7.9',
		imdbVotes: '1,013,882',
		imdbID: 'tt0371746',
		Type: 'movie',
		DVD: '30 Sep 2008',
		BoxOffice: '$319,034,126',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Iron Man 2',
		Year: '2010',
		Rated: 'PG-13',
		Released: '07 May 2010',
		Runtime: '124 min',
		Genre: 'Action, Adventure, Sci-Fi',
		Director: 'Jon Favreau',
		Writer: 'Justin Theroux, Stan Lee, Don Heck',
		Actors: 'Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow',
		Plot: "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.",
		Language: 'English, French, Russian',
		Country: 'United States',
		Awards: 'Nominated for 1 Oscar. 7 wins & 44 nominations total',
		Poster: 'https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '6.9/10' },
			{ Source: 'Rotten Tomatoes', Value: '72%' },
			{ Source: 'Metacritic', Value: '57/100' },
		],
		Metascore: '57',
		imdbRating: '6.9',
		imdbVotes: '778,975',
		imdbID: 'tt1228705',
		Type: 'movie',
		DVD: '17 Aug 2010',
		BoxOffice: '$312,433,331',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'The Hobbit: An Unexpected Journey',
		Year: '2012',
		Rated: 'PG-13',
		Released: '14 Dec 2012',
		Runtime: '169 min',
		Genre: 'Adventure, Fantasy',
		Director: 'Peter Jackson',
		Writer: 'Fran Walsh, Philippa Boyens, Peter Jackson',
		Actors: 'Martin Freeman, Ian McKellen, Richard Armitage',
		Plot: 'A reluctant Hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home, and the gold within it from the dragon Smaug.',
		Language: 'English',
		Country: 'New Zealand, United States',
		Awards: 'Nominated for 3 Oscars. 11 wins & 75 nominations total',
		Poster: 'https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.8/10' },
			{ Source: 'Rotten Tomatoes', Value: '64%' },
			{ Source: 'Metacritic', Value: '58/100' },
		],
		Metascore: '58',
		imdbRating: '7.8',
		imdbVotes: '797,203',
		imdbID: 'tt0903624',
		Type: 'movie',
		DVD: '19 Mar 2013',
		BoxOffice: '$303,003,568',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Furious',
		Year: '2017',
		Rated: 'N/A',
		Released: '30 Nov 2017',
		Runtime: '107 min',
		Genre: 'Action, Drama, History',
		Director: 'Dzhanik Fayziev, Ivan Shurkhovetskiy',
		Writer: 'Dmitriy Paltsev, Dmitriy Raevskiy, Evgeniy Raevskiy',
		Actors: 'Ilya Malakov, Aleksey Serebryakov, Aleksandr Ilin',
		Plot: 'In the 13th century, an amnesiac soldier vows to get his revenge on the Mongol army that ransacked his village.',
		Language: 'Russian, Tatar',
		Country: 'Russia',
		Awards: 'N/A',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BMmUzYzdmOWYtODdiMy00ZTI3LTgzOWEtZWE5MWJhYWY2MTIzXkEyXkFqcGdeQXVyNzUzNTQ2MjQ@._V1_SX300.jpg',
		Ratings: [{ Source: 'Internet Movie Database', Value: '6.2/10' }],
		Metascore: 'N/A',
		imdbRating: '6.2',
		imdbVotes: '3,333',
		imdbID: 'tt6054874',
		Type: 'movie',
		DVD: '25 Jun 2018',
		BoxOffice: '$9,996',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Fast & Furious 6',
		Year: '2013',
		Rated: 'PG-13',
		Released: '24 May 2013',
		Runtime: '130 min',
		Genre: 'Action, Crime, Thriller',
		Director: 'Justin Lin',
		Writer: 'Chris Morgan, Gary Scott Thompson',
		Actors: 'Vin Diesel, Paul Walker, Dwayne Johnson',
		Plot: 'Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets sidetracked with facing his presumed deceased girlfriend, Letty.',
		Language: 'English, Spanish, Russian, Japanese, Cantonese, Dutch',
		Country: 'United States, Japan, Spain, United Kingdom',
		Awards: '10 wins & 22 nominations',
		Poster: 'https://m.media-amazon.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.0/10' },
			{ Source: 'Rotten Tomatoes', Value: '71%' },
			{ Source: 'Metacritic', Value: '61/100' },
		],
		Metascore: '61',
		imdbRating: '7.0',
		imdbVotes: '386,721',
		imdbID: 'tt1905041',
		Type: 'movie',
		DVD: '29 Oct 2013',
		BoxOffice: '$238,679,850',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Face',
		Year: '1997',
		Rated: 'R',
		Released: '26 Sep 1997',
		Runtime: '105 min',
		Genre: 'Crime, Drama, Thriller',
		Director: 'Antonia Bird',
		Writer: 'Ronan Bennett',
		Actors: 'Robert Carlyle, Ray Winstone, Steve Sweeney',
		Plot: 'In the face of demise in his values, a socialist in England decides to form a gang and rob banks for a living.',
		Language: 'English',
		Country: 'United Kingdom',
		Awards: '4 wins',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BYWIzMWRjNWMtNzRkMy00NzMwLWFkNzYtODE2NTI4NDM5NWRkXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '6.7/10' },
			{ Source: 'Rotten Tomatoes', Value: '38%' },
		],
		Metascore: 'N/A',
		imdbRating: '6.7',
		imdbVotes: '4,499',
		imdbID: 'tt0119092',
		Type: 'movie',
		DVD: '25 Oct 2005',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'The Avengers',
		Year: '2012',
		Rated: 'PG-13',
		Released: '04 May 2012',
		Runtime: '143 min',
		Genre: 'Action, Adventure, Sci-Fi',
		Director: 'Joss Whedon',
		Writer: 'Joss Whedon, Zak Penn',
		Actors: 'Robert Downey Jr., Chris Evans, Scarlett Johansson',
		Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
		Language: 'English, Russian, Hindi',
		Country: 'United States',
		Awards: 'Nominated for 1 Oscar. 38 wins & 80 nominations total',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '8.0/10' },
			{ Source: 'Rotten Tomatoes', Value: '91%' },
			{ Source: 'Metacritic', Value: '69/100' },
		],
		Metascore: '69',
		imdbRating: '8.0',
		imdbVotes: '1,339,955',
		imdbID: 'tt0848228',
		Type: 'movie',
		DVD: '25 Sep 2012',
		BoxOffice: '$623,357,910',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Scraper',
		Year: '2005',
		Rated: 'N/A',
		Released: 'N/A',
		Runtime: '15 min',
		Genre: 'Short, Comedy',
		Director: 'Will Moore',
		Writer: 'Will Moore',
		Actors: 'Tino Blazejewski, Silke Matthias, Will Moore',
		Plot: 'N/A',
		Language: 'N/A',
		Country: 'N/A',
		Awards: 'N/A',
		Poster: 'N/A',
		Ratings: [],
		Metascore: 'N/A',
		imdbRating: 'N/A',
		imdbVotes: 'N/A',
		imdbID: 'tt1778894',
		Type: 'movie',
		DVD: 'N/A',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'No Time to Die',
		Year: '2021',
		Rated: 'PG-13',
		Released: '08 Oct 2021',
		Runtime: '163 min',
		Genre: 'Action, Adventure, Thriller',
		Director: 'Cary Joji Fukunaga',
		Writer: 'Neal Purvis, Robert Wade, Cary Joji Fukunaga',
		Actors: 'Daniel Craig, Ana de Armas, Rami Malek',
		Plot: 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
		Language: 'English, French, Italian, Russian, Spanish, German',
		Country: 'United Kingdom, United States',
		Awards: 'Nominated for 3 Oscars. 20 wins & 61 nominations total',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
		Ratings: [
			{ Source: 'Internet Movie Database', Value: '7.3/10' },
			{ Source: 'Rotten Tomatoes', Value: '83%' },
			{ Source: 'Metacritic', Value: '68/100' },
		],
		Metascore: '68',
		imdbRating: '7.3',
		imdbVotes: '310,313',
		imdbID: 'tt2382320',
		Type: 'movie',
		DVD: '09 Nov 2021',
		BoxOffice: '$160,891,007',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
];

export const getRandomMovieTitle = () => {
	const titles = moviesCollection.map(item => item.Title);
	return titles[Math.floor(Math.random() * titles.length)];
}
