name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: movie-service
env:
  OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: create env file
        run: |
          touch .env
          echo PORT=4000 >> .env
          echo MONGO_PORT=27017 >> .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          echo OMDB_API_KEY=${{ secrets.OMDB_API_KEY }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
      
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run Build
        run: npm run build
